ghc-options:
  "$locals": -optP-Wno-nonportable-include-path
resolver: nightly-2022-05-03
extra-deps:
  - git: https://github.com/haskell/lsp
    commit: 67a168319169d7cf4679869ed2e0cfe217743a96
    subdirs:
    - lsp
    - lsp-types
    - lsp-test
  - co-log-core-0.3.1.0@sha256:9794bdedd1391decd0e22bdfe2b11abcb42e6cff7a4531e1f8882890828f4e63,3816
